### ISSUE TITLE
Errors in Domoticz 

### ISSUE THREAD

**Issue by PvdGulik** [proditaki/OTGW-Domoticz-MQTT-Client#5]
Hello Protaki,

I've got the following errors in the Domoticz log-file and repeats every few seconds.

> "2021-12-31 19:25:29.117 Error: OTGW MQTT Client: (OTGW MQTT Client) 'onMessage' failed 'KeyError'.
> 2021-12-31 19:25:29.117 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 286 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
> 2021-12-31 19:25:29.117 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 96 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
> 2021-12-31 19:25:29.117 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 175 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/mqtt.py', function onMessage
> 2021-12-31 19:25:29.117 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 222 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMQTTPublish"

After a while it eventually reboots Domoticz...

Domoticz Crashlog:

> 35   Thread 0xe4afd200 (LWP 7305) "OTGW MQTT Clien"  __lll_lock_wait (futex=futex@entry=0xb2682c <Plugins::PythonMutex>, private=0) at lowlevellock.c:43
> 
> Thread 35 (Thread 0xe4afd200 (LWP 7305)):
> #0  __lll_lock_wait (futex=futex@entry=0xb2682c <Plugins::PythonMutex>, private=0) at lowlevellock.c:43
> #1  0xf7807f44 in __GI___pthread_mutex_lock (mutex=0xb2682c <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
> #2  0x00649cf8 in Plugins::CPlugin::Do_Work() ()
> #3  0x009a15a4 in execute_native_thread_routine ()
> #4  0xf7805494 in start_thread (arg=0xe4afd200) at pthread_create.c:486
> #5  0xf76b8568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Version Domoticz and Python:

> Version: 2021.1
> Build Hash: 8547c5b7e
> Compile Date: 2021-04-17 17:29:11
> dzVents Version: 3.1.7
> Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Don't know how to solve them, can you please help?

**Comment by proditaki** [comment]
Oh that's because of th pull request, i missed the error. 
Check now

**Comment by ZonPV** [comment]
Since this morning I installed the latest release. 
Not areal crash but some errors left in the logfile:
2022-01-08 15:51:11.572 OTGW MqttClient Arjen: Worker thread started.
2022-01-08 15:51:11.945 OTGW MqttClient Arjen: Connected to MQTT Server: 192.168.1.18:1883
2022-01-08 15:51:11.572 Status: OTGW MqttClient Arjen: Entering work loop.
2022-01-08 15:51:11.572 Status: OTGW MqttClient Arjen: Started.
2022-01-08 15:51:11.892 Status: OTGW MqttClient Arjen: Initialized version 0.0.3
2022-01-08 15:51:13.007 Error: (OTGW MqttClient Arjen) Device creation failed, Domoticz settings prevent accepting new devices.
2022-01-08 15:51:13.404 Error: (OTGW MqttClient Arjen) Device creation failed, Domoticz settings prevent accepting new devices.
2022-01-08 15:51:13.460 Error: (OTGW MqttClient Arjen) Device creation failed, Domoticz settings prevent accepting new devices.
No linenumbers about errors any more as before.  Some entries in Domoticz are updated.

**Comment by PvdGulik** [comment]
> Oh that's because of th pull request, i missed the error. 
> 
> Check now

Nope, still same problem. And the main problem is that when you want to disable your plug-in. Domoticz stops responding, message, "Problem with adding hardware"/"Probleem met toevoegen hardware", although adding hardware is allowed. The only way to get Domoticz running again is a "sudo reboot" command. After that your plug-in is disabled.

How to solve?

2022-01-08 22:07:16.429 Error: OTGW MQTT Client: (OTGW MQTT Client) 'onMessage' failed 'KeyError'.
2022-01-08 22:07:16.429 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 286 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.429 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 96 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.429 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 175 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/mqtt.py', function onMessage
2022-01-08 22:07:16.429 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 222 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMQTTPublish
2022-01-08 22:07:16.566 Error: OTGW MQTT Client: (OTGW MQTT Client) 'onMessage' failed 'KeyError'.
2022-01-08 22:07:16.566 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 286 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.566 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 96 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.566 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 175 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/mqtt.py', function onMessage
2022-01-08 22:07:16.566 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 222 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMQTTPublish
2022-01-08 22:07:16.665 Error: OTGW MQTT Client: (OTGW MQTT Client) 'onMessage' failed 'KeyError'.
2022-01-08 22:07:16.665 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 286 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.665 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 96 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:16.665 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 175 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/mqtt.py', function onMessage
2022-01-08 22:07:16.665 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 222 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMQTTPublish
2022-01-08 22:07:17.229 Error: OTGW MQTT Client: (OTGW MQTT Client) 'onMessage' failed 'KeyError'.
2022-01-08 22:07:17.229 Error: OTGW MQTT Client: (OTGW MQTT Client) ----> Line 286 in '/home/pi/domoticz/plugins/OTGW-Domoticz-MQTT-Client/plugin.py', function onMessage
2022-01-08 22:07:17.229 Error: OTGW MQTT Client: (OTGW MQTT C

When I enable the plug-in for the first time, I see this in the log:

2022-01-09 19:44:32.153 OTGW MQTT Client hardware started.
2022-01-09 19:44:32.153 Status: OTGW MQTT Client: (OTGW MQTT Client) Started.
2022-01-09 19:44:32.153 Status: OTGW MQTT Client: (OTGW MQTT Client) Entering work loop.
2022-01-09 19:44:33.118 OTGW MQTT Client: (OTGW MQTT Client) Connected to MQTT Server: 10.187.1.111:1883
2022-01-09 19:44:33.062 Status: OTGW MQTT Client: (OTGW MQTT Client) Initialized version 0.0.3
2022-01-09 19:45:36.891 Error: dzVents: Error: (3.1.7) Discarding device. No last update info found: {["deviceType"]="Temp", ["baseType"]="device", ["changed"]=true, ["name"]="Control setpoint (OTGW)", ["subType"]="LaCrosse TX3", ["protected"]=false, ["rawData"]={"27.0"}, ["signalLevel"]=2686588, ["batteryLevel"]=-480289888, ["timedOut"]=true, ["switchTypeValue"]=0, ["data"]={["_nValue"]=0, ["hardwareID"]=7908956, ["temperature"]=27.0, ["hardwareType"]="OTGW MqttClient", ["hardwareName"]="OTGW MQTT Client", ["customImage"]=0, ["unit"]=87, ["icon"]="temperature", ["protected"]=false, ["_state"]="27.0", ["hardwareTypeValue"]=94}, ["lastLevel"]=255, ["image"]="", ["deviceID"]="", ["switchType"]="On/Off", ["iconNumber"]=32, ["description"]="", ["lastUpdate"]="", ["id"]=1406}
2022-01-09 19:45:43.858 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:45:57.865 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:45:57.951 Error: dzVents: Error: (3.1.7) Discarding device. No last update info found: {["switchType"]="On/Off", ["data"]={["hardwareType"]="OTGW MqttClient", ["hardwareName"]="OTGW MQTT Client", ["_state"]="67.5", ["protected"]=false, ["customImage"]=0, ["icon"]="temperature", ["temperature"]=67.5, ["hardwareID"]=7908956, ["hardwareTypeValue"]=94, ["_nValue"]=0, ["unit"]=91}, ["timedOut"]=false, ["baseType"]="device", ["iconNumber"]=176, ["subType"]="LaCrosse TX3", ["signalLevel"]=2686588, ["image"]="", ["id"]=1410, ["batteryLevel"]=-480289888, ["protected"]=false, ["rawData"]={"67.5"}, ["name"]="CV water aanvoer (OTGW)", ["switchTypeValue"]=0, ["deviceID"]="", ["lastUpdate"]="", ["deviceType"]="Temp", ["changed"]=true, ["lastLevel"]=255, ["description"]=""}
2022-01-09 19:45:58.636 Error: dzVents: Error: (3.1.7) Discarding device. No last update info found: {["name"]="Woonkamer Temp. (OTGW)", ["deviceType"]="Temp", ["lastUpdate"]="", ["rawData"]={"20.13"}, ["changed"]=true, ["subType"]="LaCrosse TX3", ["deviceID"]="", ["switchTypeValue"]=0, ["lastLevel"]=255, ["timedOut"]=false, ["protected"]=false, ["data"]={["hardwareType"]="OTGW MqttClient", ["icon"]="temperature", ["_nValue"]=0, ["protected"]=false, ["unit"]=90, ["_state"]="20.13", ["hardwareID"]=7908956, ["hardwareName"]="OTGW MQTT Client", ["hardwareTypeValue"]=94, ["customImage"]=0, ["temperature"]=20.129999160767}, ["iconNumber"]=64, ["image"]="", ["signalLevel"]=2686588, ["batteryLevel"]=-480289888, ["id"]=1409, ["baseType"]="device", ["description"]="", ["switchType"]="On/Off"}

Followed by endlessly:

2022-01-09 19:46:53.884 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:47:07.887 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:47:21.891 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:47:35.895 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
2022-01-09 19:47:49.898 Error: OTGW MQTT Client hardware (39) thread seems to have ended unexpectedly
