### ISSUE TITLE
Error when setting the thermostat 

### ISSUE THREAD

**Issue by Xenomes** [proditaki/OTGW-Domoticz-MQTT-Client#7]
Hi,

When setting a new temperature, the following error appears in the logbook and the temperature remains at the old setting. 

Domoticz 2021.1 (Build 14046)
Python 3.7.3
ESP8266 Firmware Version 0.9.2+e9c35e9 (08-01-2022)
OTGW PIC Firmware Version 5.2

If you need more info, signal me!

```
2022-01-12 20:22:48.566  Error: OTGW: 'onMessage' failed 'ValueError':'invalid literal for int() with base 10: '65top''.
2022-01-12 20:22:48.568  Error: OTGW: Exception traceback:
2022-01-12 20:22:48.568  Error: OTGW:  ----> Line 286 in '/home/pi/domoticz/plugins/Domoticz-OTGW-firmware/plugin.py', function onMessage
2022-01-12 20:22:48.568  Error: OTGW:  ----> Line 96 in '/home/pi/domoticz/plugins/Domoticz-OTGW-firmware/plugin.py', function onMessage
2022-01-12 20:22:48.569  Error: OTGW:  ----> Line 175 in '/home/pi/domoticz/plugins/Domoticz-OTGW-firmware/mqtt.py', function onMessage
2022-01-12 20:22:48.569  Error: OTGW:  ----> Line 219 in '/home/pi/domoticz/plugins/Domoticz-OTGW-firmware/plugin.py', function onMQTTPublish
```

Update:
After a few minutes the new temperature is updated.

**Comment by Xenomes** [comment]
I have still the issue. Running all latest updates.

Domoticz 2022.1 stable
Python 3.7.3
ESP8266 Firmware Version 0.9.3+b4b8026 (16-01-2022)
OTGW PIC Firmware Version 5.3

**Comment by 0crap** [comment]
Exact same error messages I see when setting a new temperature.

`2022-12-19 09:29:56.336 Error: OTGW: Call to function 'onMessage' failed, exception details:
2022-12-19 09:29:56.337 Error: OTGW: Traceback (most recent call last):
2022-12-19 09:29:56.337 Error: OTGW: File "/home/pi/domoticz/plugins/OTGW/plugin.py", line 286, in onMessage
2022-12-19 09:29:56.337 Error: OTGW: _plugin.onMessage(Connection, Data)
2022-12-19 09:29:56.337 Error: OTGW: File "/home/pi/domoticz/plugins/OTGW/plugin.py", line 96, in onMessage
2022-12-19 09:29:56.337 Error: OTGW: self.mqttClient.onMessage(Connection, Data)
2022-12-19 09:29:56.337 Error: OTGW: File "/home/pi/domoticz/plugins/OTGW/mqtt.py", line 175, in onMessage
2022-12-19 09:29:56.337 Error: OTGW: self.on_mqtt_message_cb(topic, message)
2022-12-19 09:29:56.337 Error: OTGW: File "/home/pi/domoticz/plugins/OTGW/plugin.py", line 219, in onMQTTPublish
2022-12-19 09:29:56.337 Error: OTGW: if int(tempDev2) in Devices:
2022-12-19 09:29:56.337 Error: OTGW: ValueError: invalid literal for int() with base 10: '56top'`

**Comment by 0crap** [comment]
When not doing anything, I see often the below message in Domoticz:

`2022-12-19 09:34:02.503 Error: MQTT: Climate device invalid/unknown mode received! (otgw-C8C9A35xxxxx-thermostat: ON)
2022-12-19 09:39:02.808 Error: MQTT: Climate device invalid/unknown mode received! (otgw-C8C9A35xxxxx-thermostat: ON)
2022-12-19 09:44:02.173 Error: MQTT: Climate device invalid/unknown mode received! (otgw-C8C9A35xxxxx-thermostat: ON)
2022-12-19 09:49:02.338 Error: MQTT: Climate device invalid/unknown mode received! (otgw-C8C9A35xxxxx-thermostat: ON)` 

Please have a look into this.
Thank you!
